control_device_by_value:
  description: >-
    Set the value of a HomeSeer device.
  fields:
    ref:
      description: Device ref of the HomeSeer device to control (integer).
      example: 145
    value:
      description: New value for the HomeSeer device ref (integer).
      example: 255
